name: evie_test
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+7

environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  mapbox_gl:
    git:
      url: https://github.com/flutter-mapbox-gl/maps.git
      ref: f505fcf5c79b75c165703028af77f3af62d382ae

#  flutter_map:
#    git:
#      url: https://github.com/fleaflet/flutter_map.git
#      ref: 89f6c2bc2e773f13a4555a1bd2d5a72d4d8043c3

  mobile_scanner:
    git:
      url: https://github.com/juliansteenbakker/mobile_scanner.git
      ref: b358cdec9ae6045e46565769657ae313d7f3c957

  provider: ^6.0.3
  cupertino_icons: ^1.0.2
  firebase_core: ^1.20.0
  firebase_auth: ^3.4.2
  cloud_firestore: ^3.2.1
  cached_network_image: ^3.2.1
  image_picker: ^0.8.5+3
  firebase_storage: ^10.3.4
  shared_preferences: ^2.0.15
  google_sign_in: ^5.4.0
  sizer: ^2.0.15
  flutter_facebook_auth: ^4.4.0+1
  twitter_login: ^4.2.3
  json_annotation: ^4.6.0
  flutter_dotenv: ^5.0.2
  json_serializable: ^6.3.1
  flutter_smart_dialog: ^3.0.2
  flutter_reactive_ble: ^5.0.3
  permission_handler: ^10.0.0
  crclib: ^3.0.0
  hex: ^0.2.0
  open_settings: ^2.0.2
  get: ^4.6.5
  flutter_local_notifications: ^9.1.5
  firebase_messaging: ^13.0.2
  flutter_stripe: ^7.0.0
  cloud_functions: ^3.3.8
  dio: ^4.0.6
  webview_flutter: ^3.0.4
  connectivity_plus: ^2.3.7
  fluttertoast: ^8.0.9
  http: ^0.13.5
  carousel_slider: ^4.1.1
  sign_in_with_apple: ^4.1.0
  crypto: ^3.0.1
  geolocator: ^9.0.2
  geocoding: ^2.0.5
  animated_text_kit: ^4.2.2
  upgrader: ^4.8.1
  lottie: ^1.4.2
  open_mail_app: ^0.4.5
  step_progress_indicator: ^1.0.2
  path_provider: ^2.0.11
  file_manager: ^1.0.1
  file_picker: ^5.2.2
  percent_indicator: ^4.2.2
  modal_bottom_sheet: ^2.1.2
  flutter_svg: ^1.1.6
  map_launcher: ^2.4.0
  location: ^4.4.0
  page_transition: ^2.0.9
  flutter_compass: ^0.7.0
  paginate_firestore: ^1.0.3+1
  slider_button: ^2.0.0
  flutter_map: ^3.1.0
  flutter_slidable: ^2.0.0


dev_dependencies:
  build_runner: ^2.1.2
  json_serializable: ^6.3.1
  flutter_launcher_icons: ^0.10.0
  integration_test:
    sdk: flutter
  test: ^1.14.4

  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

  #For splash screen
  flutter_native_splash: ^2.2.6

dependency_overrides:
  test_api: ^0.4.14
  mapbox_gl:
    git:
      url: https://github.com/flutter-mapbox-gl/maps.git
      ref: f505fcf5c79b75c165703028af77f3af62d382ae
  mapbox_gl_platform_interface:
    git:
      url: https://github.com/flutter-mapbox-gl/maps.git
      ref: f505fcf5c79b75c165703028af77f3af62d382ae
      path: mapbox_gl_platform_interface
  mapbox_gl_web:
    git:
      url: https://github.com/flutter-mapbox-gl/maps.git
      ref: f505fcf5c79b75c165703028af77f3af62d382ae
      path: mapbox_gl_web

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/logo/evie_logo_icon.png'
  adaptive_icon_background: '#D7E9EF'  #masking for android
  adaptive_icon_foreground: 'assets/logo/evie_logo_icon.png'  #masking for android


flutter:
  assets:
    - assets/
    - assets/icons/
    - assets/logo/
    - assets/buttons/
    - assets/images/
    - assets/images/bike_HPStatus/
    - assets/images/splashscreen/
    - assets/files/bike_settings.json
    - env
  uses-material-design: true

  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/avenir/Avenir-Regular.ttf
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages



  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
