// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4u3Urr0u8SUOJnxKZXvULG2jEyjNYPSw',
    appId: '1:484859945311:android:9a46e56f3bbc5dfefa56ea',
    messagingSenderId: '484859945311',
    projectId: 'evie-126a6',
    storageBucket: 'evie-126a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLK6DrCZ58jpZpPO24N-nyx6djtHMxV2I',
    appId: '1:484859945311:ios:754d27de897c6908fa56ea',
    messagingSenderId: '484859945311',
    projectId: 'evie-126a6',
    storageBucket: 'evie-126a6.appspot.com',
    androidClientId: '484859945311-c5635kb2m118numsn0v441fqv9203pjh.apps.googleusercontent.com',
    iosClientId: '484859945311-vffv9uipl1ohirg96h70u78t7pbg8mq1.apps.googleusercontent.com',
    iosBundleId: 'com.evie.app',
  );
}
